from django.urls import path

from .views import (
    AboutView,
    BedAvailabilityToggleView,
    BookingRequestView,
    BookingSuccessView,
    ContactView,
    HomeView,
    LoginView,
    LogoutView,
    OwnerBedCreateView,
    OwnerBookingDecisionView,
    OwnerDashboardView,
    OwnerOfflineBookingView,
    OwnerPropertyCreateView,
    OwnerPropertyUpdateView,
    OwnerRoomCreateView,
    PGDetailView,
    RegisterView,
    SplashView,
    StudentBookingCancelView,
    StudentBookingUpdateDatesView,
    StudentBookingsView,
    StudentProfileView,
)

urlpatterns = [
    path("", SplashView.as_view(), name="splash"),
    path("home/", HomeView.as_view(), name="home"),
    path("about/", AboutView.as_view(), name="about"),
    path("contact/", ContactView.as_view(), name="contact"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
    path("pg/<int:pk>/", PGDetailView.as_view(), name="pg_detail"),
    path("profile/", StudentProfileView.as_view(), name="student_profile"),
    path("my-bookings/", StudentBookingsView.as_view(), name="student_bookings"),
    path("booking/<int:bed_id>/", BookingRequestView.as_view(), name="booking"),
    path("booking/success/<int:booking_id>/", BookingSuccessView.as_view(), name="booking_success"),
    path(
        "booking/<int:booking_id>/dates/",
        StudentBookingUpdateDatesView.as_view(),
        name="student_booking_update_dates",
    ),
    path(
        "booking/<int:booking_id>/cancel/",
        StudentBookingCancelView.as_view(),
        name="student_booking_cancel",
    ),
    path(
        "api/beds/<int:bed_id>/toggle/",
        BedAvailabilityToggleView.as_view(),
        name="bed_toggle_api",
    ),
    path("owner/dashboard/", OwnerDashboardView.as_view(), name="owner_dashboard"),
    path("owner/add-property/", OwnerPropertyCreateView.as_view(), name="add_property"),
    path("owner/pg/<int:pg_id>/edit/", OwnerPropertyUpdateView.as_view(), name="owner_edit_property"),
    path("owner/pg/<int:pg_id>/rooms/add/", OwnerRoomCreateView.as_view(), name="owner_add_room"),
    path("owner/pg/<int:pg_id>/beds/add/", OwnerBedCreateView.as_view(), name="owner_add_bed"),
    path(
        "owner/bookings/offline/",
        OwnerOfflineBookingView.as_view(),
        name="owner_add_offline_booking",
    ),
    path(
        "owner/bookings/<int:booking_id>/decision/",
        OwnerBookingDecisionView.as_view(),
        name="owner_booking_decision",
    ),
]
